apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-basic-app
  labels:
    app: my-basic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-basic-app
  template:
    metadata:
      labels:
        app: my-basic-app
    spec:
      containers:
        - name: my-basic-app
          image: ysufemrlty/my-basic-app
          ports:
            - containerPort: 5000
