apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/YusufEmirAltay/my-basic-app-deploy.git
    targetRevision: HEAD
    path: deploy/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
