apiVersion: v1
kind: Service
metadata:
  name: my-basic-app-service
spec:
  selector:
    app: my-basic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081
  type: NodePort
