name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout second Repo
        uses: actions/checkout@v2
        with:
          repository: YusufEmirAltay/my-basic-app
          token: ${{ secrets.GITHUB_TOKEN }}
          path: my-basic-app

      - name: Set Version
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Get Previous Image Tag
        run: |
          PREVIOUS_TAG=$(docker pull ysufemrlty/my-basic-app:latest 2>/dev/null && docker inspect --format='{{index .RepoTags 0}}' ysufemrlty/my-basic-app || echo "")
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Flask Image with Cache
        run: |
          docker pull ysufemrlty/my-basic-app:${{ env.PREVIOUS_TAG }} || true
          docker build --cache-from ysufemrlty/my-basic-app:${{ env.PREVIOUS_TAG }} -t ysufemrlty/my-basic-app:${{ env.IMAGE_TAG }} -f my-basic-app/app/Dockerfile my-basic-app/app
          docker push ysufemrlty/my-basic-app:${{ env.IMAGE_TAG }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i 's|ysufemrlty/my-basic-app:.*|ysufemrlty/my-basic-app:${{ env.IMAGE_TAG }}|' deploy/k8s-sources/flask/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add deploy/k8s-sources/flask/deployment.yaml
          git commit -m "Update Flask image to ${{ env.IMAGE_TAG }}"
          git push origin master
