name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout second Repo
        uses: actions/checkout@v2
        with:
          repository: YusufEmirAltay/my-basic-app
          token: ${{ secrets.GITHUB_TOKEN }}
          path: my-basic-app

      - name: Get Latest Version
        run: |
          # Get latest release tag
          VERSION=$(curl -s https://api.github.com/repos/YusufEmirAltay/my-basic-app/releases/latest | jq -r .tag_name || echo "v0")
          VERSION_NUM=$(echo $VERSION | sed 's/v//')
          NEXT_VERSION="v$((VERSION_NUM + 1))"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Flask Image with Cache
        run: |
          # Check if the previous version exists
          docker pull ysufemrlty/my-basic-app:${{ env.NEXT_VERSION }} || true
          PREVIOUS_TAG="v$(( $(echo ${{ env.NEXT_VERSION }} | sed 's/v//') - 1 ))"
          docker pull ysufemrlty/my-basic-app:${PREVIOUS_TAG} || true
          # Build the new image with cache
          docker build --cache-from ysufemrlty/my-basic-app:${PREVIOUS_TAG} -t ysufemrlty/my-basic-app:${{ env.NEXT_VERSION }} -f my-basic-app/app/Dockerfile my-basic-app/app
          docker push ysufemrlty/my-basic-app:${{ env.NEXT_VERSION }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i 's|ysufemrlty/my-basic-app:.*|ysufemrlty/my-basic-app:${{ env.NEXT_VERSION }}|' deploy/k8s-sources/flask/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add deploy/k8s-sources/flask/deployment.yaml
          git commit -m "Update Flask image to ${{ env.NEXT_VERSION }}"
          git push origin master
